name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: linux jdk17
            java: 17
            disable-samples: true
    name: CI Build ${{ matrix.nickname }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: Build
        env:
          DISABLE_SAMPLES: ${{ matrix.disable-samples }}
        run: ./gradlew build
  publish:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'spring-projects'
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
          cache: gradle
      - uses: jfrog/setup-jfrog-cli@v2
        with:
          version: 2.21.5
        env:
          JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      - name: Configure JFrog Cli
        run: |
          jf rt gradlec \
            --use-wrapper \
            --uses-plugin \
            --deploy-ivy-desc=false \
            --server-id-resolve repo.spring.io \
            --server-id-deploy repo.spring.io \
            --repo-resolve snapshot \
            --repo-deploy snapshot
          echo JFROG_CLI_BUILD_NAME=spring-shell-main >> $GITHUB_ENV
          echo JFROG_CLI_BUILD_NUMBER=$GITHUB_RUN_NUMBER >> $GITHUB_ENV
      - name: Build and Publish
        env:
          DISABLE_SAMPLES: true
        run: |
          jf rt gradle build distZip artifactoryPublish
          jf rt build-publish
